name: Build all packages

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '11 1 * * *'
  workflow_dispatch:

jobs:
  build-packages:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v18

    - name: Flake metadata
      run: >
        nix flake metadata

    - name: Flake show
      run: >
        nix flake show

    - name: Flake check
      run: >
        nix flake check --no-build --accept-flake-config

    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: geonix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build all packages
      run: >
        nix
        build --accept-flake-config .#all-packages

    - name: Build default shell
      run: >
        nix
        develop --accept-flake-config

    - name: Build postgis shell
      run: >
        nix
        develop --accept-flake-config .#postgis
        --command psql -c 'CREATE EXTENSION postgis; SELECT postgis_full_version();'
