name: Build container images

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-image:
    strategy:
      fail-fast: false
      matrix:
        image:
          - image-python
          - image-postgres
        os:
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@v18

    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: geonix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build image
      run: >
        nix build --accept-flake-config .#${{ matrix.image }}

    - name: Test image (if image-python)
      run: |
        docker load < result

        docker run -u "$(id -u):$(id -g)" geonix-python -c "import fiona; print(fiona.supported_drivers)"
      if: ${{ matrix.image == 'image-python' }}

    - name: Test image (if image-postgres)
      run: |
        docker load < result

        docker run -d -u "$(id -u):$(id -g)" -v "$(pwd):/data" -p 15432:5432 geonix-postgres

        nix develop .#psql \
        --command psql -h localhost -p 15432 -c 'CREATE EXTENSION postgis; SELECT postgis_full_version();'
      if: ${{ matrix.image == 'image-postgres' }}
