name: Update packages

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        package:
          - gdal
          - geos
          - libgeotiff
          - libspatialindex
          # - libspatialite  # not on GitHub (gaia-gis.it)
          - pdal
          - proj
          - python-fiona
          - python-pyproj
          - python-rasterio
          - python-shapely
          - qgis
          - qgis-ltr

    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Update package
        run: >
          nix develop .#nix-dev
          --accept-flake-config
          --command utils/update-version.sh ${{ matrix.package }}
        env:
          GITHUB_API_TOKEN: ${{ secrets.AGITHUB_API_TOKEN}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "pkgs(${{ matrix.package }}): automatic package update"
          body: |
            Update package to the latest upstream version.
            PR auto-generated by [create-pull-request][1].

            [1]: https://github.com/peter-evans/create-pull-request
          branch: ${{ matrix.package }}-update-action-pr
          delete-branch: true
          commit-message: "pkgs(${{ matrix.package }}): update to the latest version"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          assignees: imincik
          reviewers: imincik
          token: ${{ secrets.FLAKE_AUTOUPDATE_TOKEN }}
